version: '3.4'

services:
  gfxpixelcreator:
    image: gfxpixelcreator
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 8098"]
    ports:
      - 8098:8098
      - 5678:5678
    environment:
      - FLASK_APP=app.py
